[package]
name = "agape_layout"
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agape_core = {path = "../agape_core"}
thiserror.workspace = true
