[package]
name = "agape_layout"
description = "Layout engine for agape"
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agape_core.workspace = true
thiserror.workspace = true
