[package]
name = "counter"
version = "0.1.0"
publish = false
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
agape.workspace = true
[lints]
workspace = true

