[package]
name = "agape_core"
description = "Core type for agape"
version.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
bytemuck.workspace = true
winit.workspace = true
rand.workspace = true
