name: release.yml
on:
  pull_request:
    branches: [ "*" ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release crates
        run: sh release.sh

