name: Release
on:
  pull_request:
    branches: [ "*" ]
concurrency:
  group: release-${{github.ref}}
  cancel-in-progress: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: Release crates
        run: sh release.sh

